# -*- coding: utf-8 -*-
"""Preprocessing_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KDUZl8VBp-aSsEkBWRKPccmW2tji33aH
"""

!pip install geopandas folium matplotlib shapely osmnx networkx pandas numpy ortools

import geopandas as gpd
import folium
import matplotlib.pyplot as plt
from shapely.geometry import Point
from shapely.ops import nearest_points
import networkx as nx
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

city_boundary = gpd.read_file("/content/drive/MyDrive/Mental Health Location BDC 2024 Datafiles/toronto-boundary/citygcs_regional_mun_wgs84.shp")
ttc_routes = gpd.read_file("/content/drive/MyDrive/Mental Health Location BDC 2024 Datafiles/ttc-shapefile/TTC_SUBWAY_LINES_WGS84.shp")
bus_routes = gpd.read_file("/content/drive/MyDrive/Mental Health Location BDC 2024 Datafiles/Toronto_TTC_Routes/Toronto_TTC_Routes.shp")
schools = gpd.read_file("/content/drive/MyDrive/Mental Health Location BDC 2024 Datafiles/School locations-all types data - 4326/School locations-all types data - 4326.shp")
mental_health_services = gpd.read_file("/content/drive/MyDrive/Mental Health Location BDC 2024 Datafiles/mental-health-locations/YOUTH_MENTALHEALTH_WGS84.shp")
neighborhoods_boundary = gpd.read_file("/content/drive/MyDrive/Mental Health Location BDC 2024 Datafiles/neighborhood_shapefile/NEIGHBORHOODS_WGS84_2.shp")

# Convert .shp into visual stencils .crs
ttc_routes = ttc_routes.to_crs(city_boundary.crs)
mental_health_services = mental_health_services.to_crs(city_boundary.crs)
bus_routes = bus_routes.to_crs(city_boundary.crs)
neighborhoods = neighborhoods.to_crs(city_boundary.crs)

# Clip to Toronto
ttc_routes_clipped = gpd.clip(ttc_routes, city_boundary)
bus_routes_clipped = gpd.clip(bus_routes, city_boundary)

# Create the plot
fig, ax = plt.subplots(figsize=(12, 12))
city_boundary.plot(ax=ax, color="lightgray", edgecolor="black", alpha=0.5, label="City Boundary")
neighborhoods_boundary.plot(ax=ax, color="lightgray", edgecolor="black", alpha=1, label="City Boundary")
ttc_routes_clipped.plot(ax=ax, color="blue", linewidth=3, label="Subway Routes")
bus_routes_clipped.plot(ax=ax, color="green", linewidth=0.5, label="Bus Routes")
mental_health_services.plot(ax=ax, color="red", markersize=10, label="Adolescent Mental Health Services")
schools.plot(ax=ax, color="purple", markersize=2, label="Schools")

# Add scale bar
scale_bar = LineString([(-79.4, 43.6), (-79.389, 43.6)])  # Approx. 1 km
gpd.GeoSeries([scale_bar]).plot(ax=ax, color="black", linewidth=2, label="1 km Scale Bar")

# Add legend and title
plt.legend()
plt.title("Visualization of Toronto with Key Features")
plt.show()

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

# Step 1: Load the shapefile and Excel data
data = pd.read_excel("/content/drive/MyDrive/Mental Health Location BDC 2024 Datafiles/processed_neighborhoods_with_income_updated.xlsx")         # Replace with your Excel file path

# Step 2: Rename columns for clarity and process the data
data.columns = ['Neighborhood Name', 'Total Adolescents', 'Median Income After Tax',
                'Number', 'NEIGHBOUR_ID', 'Facility Count', 'Facilities per Population']

# Convert 'Number' in the Excel data to integers
data['Neighborhood Number'] = data['Number'].astype(int)

# Step 3: Merge the shapefile and Excel data
merged = neighborhoods.merge(
    data[['Neighborhood Number', 'Total Adolescents', 'Median Income After Tax',
          'Facility Count', 'Facilities per Population']],
    on='Neighborhood Number',  # Use 'Neighborhood Number' as the key
    how='left'
)
# Step 4: Plot the heatmaps
fig, ax = plt.subplots(1, 2, figsize=(20, 10))

# Total Adolescents Heatmap
merged.plot(
    column='Total Adolescents',
    cmap='YlGnBu',
    legend=True,
    legend_kwds={'shrink': 0.6},
    ax=ax[0]
)
ax[0].set_title('Total Adolescents (10 - 19 year olds) Heatmap')

# Median Income After Tax Heatmap
merged.plot(
    column='Median Income After Tax',
    cmap='OrRd',
    legend=True,
    legend_kwds={'shrink': 0.6},
    ax=ax[1]
)
ax[1].set_title('Median Income ($CAD) After Tax Heatmap')

plt.tight_layout()
plt.show()

neighborhoods.head()

import geopandas as gpd
import matplotlib.pyplot as plt


# Ensure CRS matches
bus_routes = bus_routes.to_crs(neighborhoods.crs)

# Spatial join: Find routes that intersect neighborhoods
routes_in_neighborhoods = gpd.sjoin(bus_routes, neighborhoods, how="inner", predicate="intersects")

# Reproject to a projected CRS
projected_routes = bus_routes.to_crs(epsg=32617)  # UTM Zone 17N for Toronto



# Visualization
fig, ax = plt.subplots(figsize=(12, 8))
neighborhoods.plot(ax=ax, color="lightgrey", edgecolor="black")
routes_in_neighborhoods.plot(ax=ax, color="blue", linewidth=0.5)
plt.title("Bus Routes Passing Through Neighborhoods")
plt.show()

# Save results
routes_in_neighborhoods.to_file("routes_in_neighborhoods.shp")

neighborhoods = neighborhoods.to_crs(epsg=3395)

import geopandas as gpd
import pandas as pd

# Load the shapefile

# Load the routes data
routes_df = pd.read_excel("routes_per_neighborhood.xlsx")

# Merge the data on AREA_NAME
merged_df = neighborhoods.merge(routes_df, on="AREA_NAME", how="left")

# Calculate the area of each neighborhood in square kilometers (or square meters)
merged_df["area"] = merged_df.geometry.area / 1e6  # Convert from square meters to square kilometers if needed

# Calculate the route density (routes per square kilometer)
merged_df["route_density"] = merged_df["route_count"] / merged_df["area"]

# Print the route density for each neighborhood
print(merged_df[["AREA_NAME", "route_density"]])