# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KO5S4-TZic2JaALM8thPkeG5i3Pg68oz
"""

# Import required libraries
import geopandas as gpd
import folium
import matplotlib.pyplot as plt
from shapely.geometry import Point
from shapely.ops import nearest_points
import networkx as nx

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

city_boundary = gpd.read_file("/content/drive/MyDrive/Mental Health Location BDC 2024 Datafiles/toronto-boundary/citygcs_regional_mun_wgs84.shp")
ttc_routes = gpd.read_file("/content/drive/MyDrive/Mental Health Location BDC 2024 Datafiles/ttc-shapefile/TTC_SUBWAY_LINES_WGS84.shp")
bus_routes = gpd.read_file("/content/drive/MyDrive/Mental Health Location BDC 2024 Datafiles/Toronto_TTC_Routes/Toronto_TTC_Routes.shp")
schools = gpd.read_file("/content/drive/MyDrive/Mental Health Location BDC 2024 Datafiles/School locations-all types data - 4326/School locations-all types data - 4326.shp")
mental_health_services = gpd.read_file("/content/drive/MyDrive/Mental Health Location BDC 2024 Datafiles/mental-health-locations/YOUTH_MENTALHEALTH_WGS84.shp")
neighborhoods = gpd.read_file("/content/drive/MyDrive/Mental Health Location BDC 2024 Datafiles/neighborhood_shapefile/NEIGHBORHOODS_WGS84_2.shp")

# Convert geographical vector data (.shp) into visual stencils (.crs)
ttc_routes = ttc_routes.to_crs(city_boundary.crs)
mental_health_services = mental_health_services.to_crs(city_boundary.crs)
bus_routes = bus_routes.to_crs(city_boundary.crs)
neighborhoods = neighborhoods.to_crs(city_boundary.crs)

from shapely.geometry import LineString

# Assuming city_boundary, neighborhoods, ttc_routes, bus_routes, and mental_health_services are GeoDataFrames
# Clip TTC and bus routes to the city boundary
ttc_routes_clipped = gpd.clip(ttc_routes, city_boundary)
bus_routes_clipped = gpd.clip(bus_routes, city_boundary)

# Create the plot
fig, ax = plt.subplots(figsize=(12, 12))
ttc_routes_clipped.plot(ax=ax, color="blue", linewidth=3, label="TTC Routes (Clipped)")
bus_routes_clipped.plot(ax=ax, color="green", linewidth=0.5, label="Bus Routes (Clipped)")
mental_health_services.plot(ax=ax, color="red", markersize=10, label="Mental Health Services")
city_boundary.plot(ax=ax, color="lightgray", edgecolor="black", alpha=0.5, label="City Boundary")
neighborhoods.plot(ax=ax, color="lightgray", edgecolor="black", alpha=0.5, label="City Boundary")


# Add scale bar
scale_bar = LineString([(-79.4, 43.6), (-79.389, 43.6)])  # Approx. 1 km
gpd.GeoSeries([scale_bar]).plot(ax=ax, color="black", linewidth=2, label="1 km Scale Bar")

# Add legend and title
plt.legend()
plt.title("Visualization of Toronto with TTC Routes and Mental Health Services")
plt.show()

neighborhoods_info = "/content/drive/MyDrive/Mental Health Location BDC 2024 Datafiles/processed_neighborhoods_with_income.xlsx"
neighborhoods_info_df = pd.read_excel(neighborhoods_info)
neighborhoods_info_df.head()

# @title Total Adolescents vs Median Income After Tax

from matplotlib import pyplot as plt
neighborhoods_info_df.plot(kind='scatter', x='Total Adolescents', y='Median Income After Tax', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

# Step 1: Load the shapefile and Excel data
data = pd.read_excel("/content/drive/MyDrive/Mental Health Location BDC 2024 Datafiles/processed_neighborhoods_with_income.xlsx")  # Replace with your Excel file path

# Step 2: Extract the neighborhood number from the AREA_NAME column (shapefile)
neighborhoods['Neighborhood Number'] = neighborhoods['AREA_NAME'].str.extract(r'\((\d+)\)')

# Convert 'Neighborhood Number' in shapefile to integer
neighborhoods['Neighborhood Number'] = neighborhoods['Neighborhood Number'].astype(int)

# Step 3: Set the correct column names and process the Excel data
data.columns = ['Neighborhood Name', 'Total Adolescents', 'Median Income After Tax', 'Neighborhood Number']
data = data.dropna(subset=['Neighborhood Name', 'Total Adolescents', 'Median Income After Tax'])

# Ensure the 'Neighborhood Number' is integer type
data['Neighborhood Number'] = data['Neighborhood Number'].astype(int)

# Step 4: Merge the shapefile and Excel data on the neighborhood number
merged = neighborhoods.merge(
    data[['Neighborhood Number', 'Total Adolescents', 'Median Income After Tax']],
    on='Neighborhood Number',
    how='left'
)

# Step 5: Check for missing data (NaN values)
print(merged[['Neighborhood Number', 'Total Adolescents', 'Median Income After Tax']].head())
print(merged[['Total Adolescents', 'Median Income After Tax']].isna().sum())

# Step 6: Plot the heatmaps
fig, ax = plt.subplots(1, 2, figsize=(20, 10))

# Plot Total Adolescents Heatmap
merged.plot(
    column='Total Adolescents',
    cmap='YlGnBu',
    legend=True,
    ax=ax[0]
)
ax[0].set_title('Total Adolescents(10 - 19 year olds) Heatmap')

# Plot Median Income After Tax Heatmap
merged.plot(
    column='Median Income After Tax',
    cmap='OrRd',
    legend=True,
    ax=ax[1]
)
ax[1].set_title('Median Income($CAD) After Tax Heatmap')

plt.tight_layout()
plt.show()

pd.set_option('display.max_rows', None)

print(neighborhoods)